# Generated by Django 3.2.7 on 2021-09-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('PaidId', models.AutoField(primary_key=True, serialize=False)),
                ('Paid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instruments_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTaDa.employeename')),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTaDa.paid')),
            ],
        ),
    ]
