# Generated by Django 3.2.7 on 2021-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('PaidId', models.AutoField(primary_key=True, serialize=False)),
                ('Paid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TADA',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instruments_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.CharField(max_length=100)),
            ],
        ),
    ]
